apiVersion: v1
kind: Pod
metadata:
  name: kaniko3
  namespace: kaniko
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sh", "-c", "sleep infinity"]
    env:
    - name: HOME
      value: /workspace
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    workingDir: /workspace
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["/bin/sh", "-c", "sleep infinity"]
    env:
    - name: HOME
      value: /workspace
    volumeMounts:
      - name: docker-config
        mountPath: /kaniko/.docker
      - name: workspace
        mountPath: /workspace
    workingDir: /workspace
  restartPolicy: Never
  volumes:
    - name: docker-config
      secret:
        secretName: ghcr-token
    - name: workspace
      emptyDir: {}
