apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
      containers:
      - name: go
        image: go-minikube-app
        ports:
        - containerPort: 8080
      
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  selector:
    app: go
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
