rendering_servers:
  vars:
    ansible_user: ansiblerunner
    ansible_connection: winrm
    ansible_winrm_transport: certificate
    ansible_winrm_cert_pem: /path/client_cert.pem
    ansible_winrm_cert_key_pem: /path/client_key.pem
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
  hosts:
    pc1:
     ansible_host: 10.223.743.256
  